version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: time-series-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    restart: always
    
  api:
    build: 
      context: ./python-dev-container
      dockerfile: Dockerfile
    container_name: time-series-api
    ports:
      - "8080:8000"
    environment:
      - EMAIL_PASSWORD=silFida-lIonez9-otrAsl
    restart: always
